# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0010_auto_20160103_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('closed_rsvp', models.BooleanField(default=False, help_text='Whether or not to let members RSVP themselves. Used mostly for regattas.')),
                ('going', models.ManyToManyField(blank=True, to='main.TeamMember')),
            ],
        ),
    ]
