# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160101_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='going',
            field=models.ManyToManyField(blank=True, to='main.TeamMember'),
        ),
    ]
