# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160102_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='closed_rsvp',
            field=models.BooleanField(default=False, help_text='Whether or not to let members RSVP themselves. Used mostly for regattas.'),
        ),
    ]
