# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160123_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 1, 23, 19, 49, 24, 25000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
