# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_pinned_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbs'),
        ),
    ]
