# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160121_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned_post',
            field=models.BooleanField(default=False),
        ),
    ]
