# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.CharField(choices=[(b'1', b'1st'), (b'2', b'2nd'), (b'3', b'3rd'), (b'4', b'4th'), (b'5', b'5th'), (b'0', b'Other')], max_length=1)),
                ('sailing_level', models.CharField(choices=[(b'1', b'Beginner'), (b'2', b'Intermediate'), (b'3', b'Race')], max_length=1)),
                ('eboard_pos', models.CharField(blank=True, max_length=50)),
                ('dues_paid', models.DateField()),
                ('avatar', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
