# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='dues_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='sailing_level',
            field=models.CharField(choices=[(b'1', b'Beginner'), (b'2', b'Intermediate'), (b'3', b'Race')], default=b'1', max_length=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='year_level',
            field=models.CharField(choices=[(b'1', b'1st'), (b'2', b'2nd'), (b'3', b'3rd'), (b'4', b'4th'), (b'5', b'5th'), (b'0', b'Other')], default=b'1', max_length=1),
        ),
    ]
