# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20151229_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year_level', models.CharField(choices=[(b'', b'Year Level'), (b'1', b'1st'), (b'2', b'2nd'), (b'3', b'3rd'), (b'4', b'4th'), (b'5', b'5th'), (b'6', b'Other')], default=b'1', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='teammember',
            name='year_level',
            field=models.CharField(choices=[(b'', b'Year Level'), (b'1', b'1st'), (b'2', b'2nd'), (b'3', b'3rd'), (b'4', b'4th'), (b'5', b'5th'), (b'6', b'Other')], default=b'1', max_length=1),
        ),
    ]
