# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_request_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='was_checked',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
