# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20151231_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='year_level',
            field=models.CharField(choices=[(b'1', b'1st'), (b'2', b'2nd'), (b'3', b'3rd'), (b'4', b'4th'), (b'5', b'5th'), (b'6', b'Other')], default=b'1', max_length=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='year_level',
            field=models.CharField(choices=[(b'1', b'1st'), (b'2', b'2nd'), (b'3', b'3rd'), (b'4', b'4th'), (b'5', b'5th'), (b'6', b'Other')], default=b'1', max_length=1),
        ),
    ]
