# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160101_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='year_level',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', 'Other')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='sailing_level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Race')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='year_level',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', 'Other')], default='1', max_length=1),
        ),
    ]
