# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0002_auto_20160122_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpage',
            old_name='ccontent',
            new_name='content',
        ),
    ]
