# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Folder'),
        ),
    ]
