# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20160311_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
